common:
  frame_id: "velodyne"
  data_set: "utbm" # "my" # 
  
IMU:
  acc_n: 2000
  gyr_n: 0.0173
  acc_w: 2
  gyr_w: 0.00025

preprocessing:
  lidar_topic: "/merged_cloud" #
  ds_rate: 2
  line_num: 48

lidar_odometry:
  max_num_iter: 12
  scan_match_cnt: 1
  if_to_deskew: false

backend_fusion:
  max_num_iter: 15
  loop_closure_on: true
  local_map_width: 50
  lc_search_radius: 15
  lc_map_width: 25
  lc_icp_thres: 0.2
  slide_window_width: 3
  imu_topic: "/imu_raw"
  lidar_const: 7.5
  mapping_interval: 2
  lc_time_thres: 60.0
  surf_dist_thres: 0.12
  kd_max_radius: 1.0
  save_pcd: true

#extrinsic imu to lidar
  ql2b_w: 0
  ql2b_x: 0.707106781186548
  ql2b_y: 0.707106781186548
  ql2b_z: 0

  tl2b_x: 0
  tl2b_y: -0.005
  tl2b_z: 0.069
